//! The end-to-end path a consumer actually runs: an arbitrary document is scanned, its hashes go
//! into a policy, and that policy is rendered as a response header.
//!
//! This is the oracle that matches the deployment. The shell is the least trusted input in the
//! chain — it is generated by a bundler, mounted from a volume, or replaced under a running
//! process — and its content reaches a response header. Nothing in it may steer that header:
//! not the length of a script, not a `>` inside an attribute value, not a NUL, and not a document
//! engineered so that the scan produces something the builder would have rejected.

use arbitrary::{Arbitrary, Unstructured};
use csp_shell::presets::cloudflare;
use csp_shell::{scan_shell, Csp, Source, SourceDirective};

use crate::support;

/// The consumer's configuration surface, exactly as a real one exposes it.
#[derive(Arbitrary, Debug)]
pub struct Deployment {
    pub shell: String,
    pub script_nonce: bool,
    pub turnstile: bool,
    pub extra_connect_src: Vec<String>,
}

/// Decodes `data` into a deployment and runs it.
///
/// The decode is `arbitrary_take_rest` over the raw bytes, which is exactly what
/// `libfuzzer_sys::fuzz_target!` does for a typed argument — so a corpus entry a campaign found
/// means the same thing here as it did under the fuzzer.
///
/// # Panics
///
/// See [`run`].
pub fn check(data: &[u8]) {
    let Ok(deployment) = Deployment::arbitrary_take_rest(Unstructured::new(data)) else {
        return;
    };
    run(&deployment);
}

/// Scans the shell, assembles the preset around it, and asserts the header that reaches the wire.
///
/// # Panics
///
/// If the document steered the header — out of the field-value alphabet, into an extra directive,
/// past one of the preset's restrictions, or into a hash count the scan does not agree with.
pub fn run(deployment: &Deployment) {
    let scan = scan_shell(&deployment.shell);

    let mut csp = Csp::spa_wasm().with_scan(&scan);
    if deployment.script_nonce {
        csp = cloudflare::script_nonce(csp);
    }
    if deployment.turnstile {
        csp = cloudflare::turnstile(csp);
    }
    // A config-derived origin list: the vector the typed source expressions exist for. Whatever
    // survives the parse is what a real consumer would have handed the builder.
    let extra: Vec<Source> = deployment
        .extra_connect_src
        .iter()
        .filter_map(|origin| Source::parse(origin).ok())
        .collect();
    if let Ok(extended) = csp.clone().extend(SourceDirective::ConnectSrc, extra) {
        csp = extended;
    }

    let policy = csp.build();
    let headers = policy.headers();
    let rendered = &headers.content_security_policy;

    support::assert_field_value(rendered);
    support::assert_structure(rendered);

    // The preset is ten directives; a nonce adds none and Turnstile adds `frame-src`. Anything
    // else means a `;` arrived from an input rather than from the builder.
    let expected_directives = 10 + usize::from(deployment.turnstile);
    assert_eq!(
        rendered.split("; ").count(),
        expected_directives,
        "unexpected directive count in {rendered:?}"
    );

    // The preset's restrictions survive every input.
    for required in [
        "default-src 'self'",
        "object-src 'none'",
        "base-uri 'none'",
        "form-action 'self'",
        "frame-ancestors 'none'",
    ] {
        assert!(
            rendered.contains(required),
            "{required} lost from {rendered:?}"
        );
    }

    let script_src =
        support::directive_of(rendered, "script-src").expect("the preset sets script-src");
    assert!(script_src.starts_with("script-src 'self' 'wasm-unsafe-eval'"));
    assert!(
        !script_src.contains("'unsafe-inline'"),
        "the shell admitted inline script: {script_src:?}"
    );

    // Every hash the scan produced reached the header, and nothing else that looks like one did.
    for hash in &scan.hashes {
        assert!(
            script_src.contains(&hash.to_string()),
            "{hash} lost from {script_src:?}"
        );
    }
    assert_eq!(
        script_src.matches("'sha256-").count(),
        scan.hashes.len(),
        "hash count changed between the scan and the header: {script_src:?}"
    );

    assert_eq!(
        headers.cache_control.is_some(),
        deployment.script_nonce,
        "the cache obligation must track the nonce and nothing else"
    );
}
