//! The end-to-end path a consumer actually runs: an arbitrary document is scanned, its hashes go
//! into a policy, and that policy is rendered as a response header.
//!
//! This is the target that matches the deployment. The shell is the least trusted input in the
//! chain — it is generated by a bundler, mounted from a volume, or replaced under a running
//! process — and its content reaches a response header. Nothing in it may steer that header:
//! not the length of a script, not a `>` inside an attribute value, not a NUL, and not a
//! document engineered so that the scan produces something the builder would have rejected.

#![no_main]

use arbitrary::Arbitrary;
use csp_shell::{cloudflare, scan_shell, Csp};
use libfuzzer_sys::fuzz_target;

#[derive(Arbitrary, Debug)]
struct Deployment {
    shell: String,
    /// The consumer's configuration surface, exactly as a real one exposes it.
    script_nonce: bool,
    turnstile: bool,
    extra_connect_src: Vec<String>,
}

fuzz_target!(|deployment: Deployment| {
    let scan = scan_shell(&deployment.shell);

    let mut csp = Csp::spa_wasm().with_scan(&scan);
    if deployment.script_nonce {
        csp = cloudflare::script_nonce(csp);
    }
    if deployment.turnstile {
        csp = cloudflare::turnstile(csp).expect("turnstile uses literal source expressions");
    }
    // A config-derived origin list: the vector the validation exists for.
    if let Ok(extended) = csp.clone().extend("connect-src", &deployment.extra_connect_src) {
        csp = extended;
    }

    let policy = csp.build();
    let headers = policy.headers();
    let rendered = &headers.content_security_policy;

    assert!(
        rendered.bytes().all(|byte| (0x20..=0x7e).contains(&byte)),
        "the shell steered the header out of the HTTP field-value range: {rendered:?}"
    );
    assert!(!rendered.contains(','), "policy separator in {rendered:?}");

    // The preset is ten directives; a nonce adds none and Turnstile adds `frame-src`. Anything
    // else means a `;` arrived from an input rather than from the builder.
    let expected_directives = 10 + usize::from(deployment.turnstile);
    assert_eq!(
        rendered.split("; ").count(),
        expected_directives,
        "unexpected directive count in {rendered:?}"
    );

    // The preset's restrictions survive every input.
    for required in [
        "default-src 'self'",
        "object-src 'none'",
        "base-uri 'none'",
        "form-action 'self'",
        "frame-ancestors 'none'",
    ] {
        assert!(rendered.contains(required), "{required} lost from {rendered:?}");
    }

    let script_src = rendered
        .split("; ")
        .find(|segment| segment.starts_with("script-src "))
        .expect("the preset sets script-src");
    assert!(script_src.starts_with("script-src 'self' 'wasm-unsafe-eval'"));
    assert!(
        !script_src.contains("'unsafe-inline'"),
        "the shell admitted inline script: {script_src:?}"
    );

    // Every hash the scan produced reached the header, and nothing else that looks like one did.
    for hash in &scan.hashes {
        assert!(script_src.contains(hash.as_str()), "{hash} lost from {script_src:?}");
    }
    assert_eq!(
        script_src.matches("'sha256-").count(),
        scan.hashes.len(),
        "hash count changed between the scan and the header: {script_src:?}"
    );

    assert_eq!(
        headers.cache_control.is_some(),
        deployment.script_nonce,
        "the cache obligation must track the nonce and nothing else"
    );
});
